### PR TITLE
Import `Base.@kwdef` for compatibility with Julia versions below 1.9

### PR DESCRIPTION
**Pull request by sambuddhac**
This is a minor code edit to fix the failure to precompile error. i have replaced the @kwdef with Base.@kwdef, since otherwise the code won't precompile (and consequently, work)

### CODE REVIEW

**Review by GabrielKS — CHANGES_REQUESTED** [review]
@sambuddhac what version of Julia you are using? `@kwdef` gets exported from `Base` as of 1.9 and so this works without the change for me, so I am assuming earlier than that.

Anyway, my preference for supporting versions earlier than 1.9 would be to import `@kwdef`. Adding this line to the imports at the top of `src/InfrastructureSystems.jl` should work:
```julia
import Base: @kwdef  # for Julia versions earlier than 1.9
```
and then prefixing with `Base` shouldn't be required:
Screenshot 2024-07-31 at 1 35 31 PM

**Comment by sambuddhac** [comment]
> @sambuddhac what version of Julia you are using? `@kwdef` gets exported from `Base` as of 1.9 and so this works without the change for me, so I am assuming earlier than that.
> 
> Anyway, my preference for supporting versions earlier than 1.9 would be to import `@kwdef`. Adding this line to the imports at the top of `src/InfrastructureSystems.jl` should work:
> 
> ```julia
> import Base: @kwdef  # for Julia versions earlier than 1.9
> ```
> 
> and then prefixing with `Base` shouldn't be required: Screenshot 2024-07-31 at 1 35 31 PM
> 
> Thanks for catching the compatibility issue.

Thanks @GabrielKS . I am using Julia 1.8. In that case, would yall mind updating the README (and perhaps the doc pages too) with these set of instructions? The README for PowerSystems.jl at least says Julia 1.6+ is good. Thanks bunches !!!

Sam

**Comment by GabrielKS** [comment]
> 
> Thanks @GabrielKS . I am using Julia 1.8. In that case, would yall mind updating the README (and perhaps the doc pages too) with these set of instructions? The README for PowerSystems.jl at least says Julia 1.6+ is good. Thanks bunches !!!
> 
> Sam

Ah, I meant that that _this PR_ should add that import (rather than adding the prefix) such that it _does_ work out of the box for 1.6+. I'd be happy to do that if you don't want to.

**Comment by sambuddhac** [comment]
> > Thanks @GabrielKS . I am using Julia 1.8. In that case, would yall mind updating the README (and perhaps the doc pages too) with these set of instructions? The README for PowerSystems.jl at least says Julia 1.6+ is good. Thanks bunches !!!
> > Sam
> 
> Ah, I meant that that _this PR_ should add that import (rather than adding the prefix) such that it _does_ work out of the box for 1.6+. I'd be happy to do that if you don't want to.

@GabrielKS Oh, my apologies for the misunderstanding. I will be extremely glad to take care of this in just a couple hours (right now, driving home from work and then I need to take care of some personal stuff and then, will be quickly on this PR to fix it). Thanks so much and please allow me a couple hours or so for the PR revision. 
Sam

**Comment by sambuddhac** [comment]
Hi @GabrielKS , I just incorporated your suggestion. Once this is approved and merged, I will update the same edit on the other repos (following, successful testings). Thanks !!!

**Review by GabrielKS — APPROVED** [review]
Looks good, thanks!

**Comment by sambuddhac** [comment]
> Looks good, thanks!

@GabrielKS thanks a lot !!! I unfortunately, don't have write access to the repository. Would you please merge? Or, alternatively, if you grant me write-access, I will be very happy to rebase/merge/squash-n-merge (on main or develop) whichever is your preferred modus-operandi. :)

**Pull request merged**
